### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by arcanjl** [a-ws-m/FVTT-Long-Rest-HD-Healing-5e#11]
Everytime I update my mods, this one updates from 3.0 -> 3.0 LOL

**Comment by Gawdl3y** [comment]
This is due to the module author forgetting to update the version number in the ["download" property in manifest.json](https://github.com/a-ws-m/FVTT-Long-Rest-HD-Healing-5e/blob/master/module.json#L26).

@a-ws-m Since you're using the master branch's manifest directly, you should be able to resolve this by simply updating the remaining references of `3.3.0` to `3.3.1`, no need for tagging a 3.3.2 release.

**Comment by a-ws-m** [comment]
Thanks for pointing that out! That's been fixed now.
